### ISSUE TITLE
How to edit models?

### ISSUE THREAD

**Issue by LeedleFace** [adierking/unplug#5]
Is there any way of turning the .dat files into files for editing in blender?

**Comment by adierking** [comment]
Not yet. I'd like to work on it but I haven't had the time or energy for it in a while.

There is [FinModelUtility](https://github.com/MeltyPlayer/FinModelUtility) which can view/extract models but not edit them. The plan is to eventually port the code from that over.

Also, someone did dump all of the models from the Wii version of the game. I'm not going to link it here for copyright reasons, but you can find it if you join the [Chibi-Robo Discord](https://discord.gg/ymNDqTyjRQ) and check the pins in the #fangames-and-modding channel.
